name: Hello Workflow
description: Initial Checks
enabled: true
triggers:
- type: cron
  schedule: "0 * * * * *"

nodes:

- id: hello-world
  type: shell
  cmd: echo "Hello, World!"
  env: {}
  when: null
  retry: null
  timeout: null

- id: my-system
  type: shell
  cmd: echo "Running on $(uname -s) with $(uname -r)"
  env: {}
  when: null
  retry: null
  timeout: null
  
- id: timestamp
  type: shell
  cmd: date
  env: {}
  when: null
  retry: null
  timeout: null
